modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="enemyexpansion"
version="2.3.5"
displayName="Enemy Expansion"
displayURL="https://infernalstudios.org/"
logoFile="logo.png"
credits="Made with MCreator!"
authors="nekomaster1000"
description="Adding more enemies to Minecraft!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.enemyexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.enemyexpansion]]
    modId="geckolib3"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enemyexpansion]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

