modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="enemyexpansion"
version="2.1.0"
displayName="Enemy Expansion"
credits="Made with MCreator!"
displayURL="https://infernalstudios.org/"
logoFile="logo.png"
authors="nekomaster1000"
description='''
Adding more enemies to Minecraft!
'''

[[dependencies.enemyexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.enemyexpansion]]
    modId="geckolib3"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enemyexpansion]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enemyexpansion]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

